### ISSUE TITLE
Issues setting this up locally

### ISSUE THREAD

**Issue by thexavismith** [ttimsmith/GoodStuff-Showbot#1]
Maybe tomorrow you can help me get this running locally?

**Comment by willmanduffy** [comment]
Sure, happy to help you out. I know exactly what your issues are. I tore out some code and kept it local because it was messing up Heroku. I'm on the train home now from some errands, but I should be available 1:30 at the earliest. Let me know when is good for you.

**Comment by thexavismith** [comment]
How about 3:30 Central? After I record TIRP?

**Comment by willmanduffy** [comment]
Sounds great!
